#!/usr/bin/env bash
#Script that displays 'To infinity and beyond' indefinitely, with 'sleep 2' in between each iteration and 'I am invincible!!!' when it receives a SIGTERM signal

while true; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincilble!!!"' SIGTERM
done
