#!/usr/bin/env bash
#This script displays 'Hours' from 0 - 12 and 'Minutes' from 1 - 59.
hour=-1
while [ $((++hour)) -le 12 ]; do
	echo Hour: $hour
	minute=0
	while [ $((++minute)) -le 59 ]; do
		echo $minute
	done
done 
